# Generated by Django 6.0.6 on 2026-07-04 18:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('duration_months', models.PositiveSmallIntegerField(choices=[(1, 'Mensual'), (3, 'Trimestral'), (6, 'Semestral'), (12, 'Anual')])),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['duration_months', 'price'],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=django.utils.timezone.localdate)),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Activa'), ('pending', 'Pendiente'), ('suspended', 'Suspendida'), ('cancelled', 'Cancelada'), ('expired', 'Vencida')], default='pending', max_length=20)),
                ('renewal_count', models.PositiveIntegerField(default=0)),
                ('suspended_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='members.member')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='memberships.membershipplan')),
            ],
            options={
                'ordering': ['-end_date'],
                'indexes': [models.Index(fields=['status', 'end_date'], name='memberships_status_e653e8_idx'), models.Index(fields=['member', 'status'], name='memberships_member__3515be_idx')],
            },
        ),
    ]
