# Generated by Django 6.0.6 on 2026-07-04 18:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('notification_type', models.CharField(choices=[('membership_expiration', 'Vencimiento de membresia'), ('reservation_confirmed', 'Reserva confirmada'), ('promotion', 'Promocion especial')], max_length=40)),
                ('subject', models.CharField(max_length=160)),
                ('body', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['notification_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=160)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('queued', 'En cola'), ('sent', 'Enviada'), ('failed', 'Fallida')], default='queued', max_length=20)),
                ('scheduled_for', models.DateTimeField(default=django.utils.timezone.now)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='members.member')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notifications.notificationtemplate')),
            ],
            options={
                'ordering': ['-scheduled_for'],
                'indexes': [models.Index(fields=['status', 'scheduled_for'], name='notificatio_status_2e04f4_idx')],
            },
        ),
    ]
