# Generated by Django 6.0.6 on 2026-07-04 20:09

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rotated_at', models.DateTimeField(blank=True, null=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qr_credential', to='members.member')),
            ],
            options={
                'ordering': ['member__first_name', 'member__last_name'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('check_out_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(choices=[('qr', 'QR'), ('manual', 'Manual')], default='qr', max_length=20)),
                ('notes', models.CharField(blank=True, max_length=180)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='members.member')),
            ],
            options={
                'ordering': ['-check_in_at'],
                'indexes': [models.Index(fields=['member', 'check_in_at'], name='attendance__member__699ed1_idx'), models.Index(fields=['check_out_at'], name='attendance__check_o_d682aa_idx')],
            },
        ),
    ]
